version: "3.8"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.11.3"
  INSTALL_NODE_VERSION: "20.1.0"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  flask-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod

      target: production
      args:
        <<: *build_args
    image: chochow-prod
    # image: 730866387406.dkr.ecr.us-east-1.amazonaws.com/devops:chochow-prod
    #x-aws-pull_credentials: "arn:aws:secretsmanager:us-east-1:12345:secret:${{secrets.DockerHubAccessToken}}"
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

volumes:
  node-modules:
