name: Deploy Container image to AWS ECR
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
    aws_ecr_dockerfile_deploy:
        runs-on: ubuntu-latest
        name: Deploy Container image to AWS ECR
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy container image to AWS ECR
              uses: nyakaz73/aws-ecr-deploy@v0.14
              id: deploy 
              with:
                access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                region: ${{ secrets.AWS_REGION }}
                aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
                repo_uri: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devops
                image_name: chochow

                use_compose: true

            # - name: Save state
            #   run: echo "::save-state name={name}::{value}"

            # - name: Set output
            #   run: echo "::set-output name={name}::{value}"